---

- name: Download pip
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_dest }}"

- name: Install pip (with options)
  command: "{{ pip_command_python }} {{ pip_download_dest }}/{{ pip_download_filename }} {{ pip_install_options }}"
  when: pip_install_options is defined

- name: Install pip (without options)
  command: "{{ pip_command_python }} {{ pip_download_dest }}/{{ pip_download_filename }}"
  when: pip_install_options is not defined

- name: Delete downloaded file
  file:
    path: "{{ pip_download_dest }}/{{ pip_download_filename }}"
    state: absent
